rm(list=ls())
library(bit64)
library(data.table)
library(tidyr)
library(tidyverse)

filepath="C:/CoCoNet/model_outputs"

# Read in the data generated by CoCoNet without treatment (counterfactual: run0) and with treatment (run1)

counterfactual=list.files(path = filepath, pattern=c("CF"))##CF_00 (no control); CF_no_CoTS


#outputs=outputs[-6]#remove counterfactual


for (d in outputs) {
  
  myfile=paste(filepath,counterfactual[1],sep="/")##To edit the new no-cots cf  
  
  myfile2=paste(filepath,d,sep="/")
  
  strat=myfile2
  strat<-sub(paste(filepath,"/",sep=""), "", strat)
  strat<-sub("vessels.csv","",strat)
  
  
  run0 <- fread(myfile, header = TRUE)
  run1 <- fread(myfile2, header = TRUE)
  
  # Year range for plots
  first_year <- 2018##to coincide with ReefMod
  treat_year <- 2019
  last_year <- 2050
  north_lat <- -10
  south_lat <- -25
  
  
  # Standardise ordering of rows: ensemble/year/reef
  run0 <- arrange(run0, Ensemble, Year, Reef_ID)
  run1 <- arrange(run1, Ensemble, Year, Reef_ID)
  
  # Add a column for total coral cover (%) for each reef
  run0$Coral_cover <- 100 * rowSums(run0[ , c(10:15)])
  run1$Coral_cover <- 100 * rowSums(run1[ , c(10:15)])
  
  # Add a column containing coral area (ha) for each reef (assuming sites ~ 10 ha)
  # Coral area (in km^2) = 0.0764 x Reef_sites x coral_cover 
  run0$Coral_area <- 0.0764 * run0$Reef_sites * (run0$Coral_cover / 100) 
  run1$Coral_area <- 0.0764 * run1$Reef_sites * (run1$Coral_cover / 100)
  
  # Add a column for adult CoTS density
  run0$CoTS_density <- rowSums(run0[ , c(17:20)])
  run1$CoTS_density <- rowSums(run1[ , c(17:20)])
  
  # Add a column for CoTS active outbreaks (0 if CoTS per tow < 1.0, otherwise 1 )
  run0$CoTS_active <- 0.5 * ((run0$CoTS_density - 1.0) + abs(run0$CoTS_density - 1.0)) / (run0$CoTS_density - 1.0)
  run1$CoTS_active <- 0.5 * ((run1$CoTS_density - 1.0) + abs(run1$CoTS_density - 1.0)) / (run1$CoTS_density - 1.0)
  
  # Add a column for CoTS all outbreaks (0 if CoTS per tow < 0.22, otherwise 1 )
  run0$CoTS_total <- 0.5 * ((run0$CoTS_density - 0.22) + abs(run0$CoTS_density - 0.22)) / (run0$CoTS_density - 0.22)
  run1$CoTS_total <- 0.5 * ((run1$CoTS_density - 0.22) + abs(run1$CoTS_density - 0.22)) / (run1$CoTS_density - 0.22)
  
  ##----------------------------------------------------------------
  # Select the reefs culled at least 8 times
  culled<-run1[which(run1$Control_visits_cumulative >7), ]
  culled=unique(culled$Reef_ID)

#  run1_culled<-run1[which(run1$Reef_ID %in% culled), ]
#  run0_culled<-run0[which(run0$Reef_ID %in% culled), ]
  
  ##Keep All
  Totculled<-run1[which(run1$Control_visits_cumulative >0), ]
  Totculled<-subset(Totculled, select=c(Ensemble,Year,Reef_ID,Control_visits_cumulative))
  
  save(Totculled, file=paste(filepath,"/Total_Reefculled_new",strat,".R",sep=""))

  # 
  # # Extract years of interest
  #run0_t <- run0_culled[which(run0_culled$Year >= first_year & run0_culled$Year <= last_year), ]##run0/run0_culled
  #run1_t <- run1_culled[which(run1_culled$Year >= first_year & run1_culled$Year <= last_year), ]##run1/run1_culled
  ##----------------------------------------------------------------  
  
  # Remove the Reef_ID and Region (which can't be averaged)
  #run0 = subset(run0, select = -c(Reef_ID, Region))
  #run1 = subset(run1, select = -c(Reef_ID, Region))
  
  # Extract years of interest
   run0_t <- run0[which(run0$Year >= first_year & run0$Year <= last_year), ]
   run1_t <- run1[which(run1$Year >= first_year & run1$Year <= last_year), ]
  
  # Extract latitudinal zone of interest
  run0_y <- run0_t[which(run0_t$Latitude < north_lat & run0_t$Latitude >= south_lat), ]
  run1_y <- run1_t[which(run1_t$Latitude < north_lat & run1_t$Latitude >= south_lat), ]
  # 
  
   # Generate new data tables with model ensemble, year, coral cover (%), coral area (ha), CoTS density, total outbreaks (% reefs) and active outbreaks (% reefs) 
  model0 <- data.table(Ensemble = run0_y$Ensemble)##run0_m
  model0$Year <- run0_y$Year
  model0$Reef_ID <- run0_y$Reef_ID
  model0$Coral_cover <- run0_y$Coral_cover
  model0$Coral_area <- run0_y$Coral_area
  model0$CoTS_density <- run0_y$CoTS_density
  model0$CoTS_total <- run0_y$CoTS_total
  model0$CoTS_active <- run0_y$CoTS_active
  # 
  #Need to Keep Reef surveyed area for weighted benefit
  model1 <- data.table(Ensemble = run1_y$Ensemble)##run1_m
  model1$Year <- run1_y$Year
  model1$Reef_ID <- run1_y$Reef_ID
  model1$Reefarea <- run1_y$Reef_sites*0.1 #convert reef Area to km2
  model1$Coral_cover <- run1_y$Coral_cover
  model1$Coral_area <- run1_y$Coral_area
  model1$CoTS_density <- run1_y$CoTS_density
  model1$CoTS_total <- run1_y$CoTS_total
  model1$CoTS_active <- run1_y$CoTS_active

  # # Difference between scenario and counterfactual
  model_delta <- data.table(Ensemble = run0_y$Ensemble)
  model_delta$Year <- model1$Year
  model_delta$Reef_ID <- model1$Reef_ID
  #Need to Keep Reef surveyed area for weighted benefit
  model_delta$Reefarea <- model1$Reefarea
  model_delta$Coral_cover <- model1$Coral_cover - model0$Coral_cover
  model_delta$Coral_area <- (model1$Coral_area - model0$Coral_area )#* conversion  # total coral area in Km2--OLD
  model_delta$CoTS_density <- model1$CoTS_density - model0$CoTS_density
  model_delta$CoTS_total <- model1$CoTS_total - model0$CoTS_total
  model_delta$CoTS_active <- model1$CoTS_active - model0$CoTS_active
  
  
  
  save(model1,model_delta, file=paste(filepath,"/ALLoutputs_new",strat,".R",sep=""))
  #save(model0, file=paste(filepath,"/Counterfactual_noCoTS.R",sep=""))
  
  ##-----------------
  ##Only culled Reefs
  ##-----------------

  run0_culled<-model0[which(model0$Reef_ID %in% culled), ]
  run1_culled <-model1[which(model1$Reef_ID %in% culled), ]
  delta_culled<-model_delta[which(model_delta$Reef_ID %in% culled), ]
  
  save(run0_culled,run1_culled,delta_culled, file=paste(filepath,"/culledoutputs_new",strat,".R",sep=""))
  
  
}

